/// <reference types="vite/client" />

// Generated by vite/editorTypesPlugin.ts at build time.
declare module 'virtual:editor-types' {
  const types: { screeps: string; dojo: Record<string, string> };
  export default types;
}
