'use strict';

// Generates docker-compose.override.yml from the bot profiles declared in .env.
//
// Docker Compose cannot enumerate a dynamic set of variables, and a bind mount
// is fixed when the container is created — so every registered codebase has to
// be mounted up front for name-based switching to be free at run time. This
// runs HOST-side (the container has no access to the host filesystem or the
// Docker daemon) from `npm run ui`, `npm test`, and `npm run bots:sync`.
//
// generate() is pure so it can be unit-tested; write() is the only I/O.
const fs = require('fs');
const path = require('path');
const { parse } = require('../src/server/envFile');
const botProfiles = require('../src/botProfiles');

const ROOT = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const OVERRIDE_PATH = path.join(ROOT, 'docker-compose.override.yml');
const SERVICES = ['dojo', 'ui'];
const HEADER = [
	'# GENERATED by scripts/composeOverride.js — do not edit.',
	'# Mounts every bot profile from .env read-only at /bots/<name>.',
	'# Regenerate with: npm run bots:sync',
	''
].join('\n');

// Compose accepts unquoted scalars, but Windows paths routinely contain spaces
// and a leading drive letter reads as a YAML tag to some parsers. Double-quote
// everything and escape what YAML requires inside double quotes.
function yamlQuote(value) {
	return '"' + String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

// The `default` profile is already mounted by the base compose file's single
// interpolated line, so re-mounting it here would only duplicate it.
// `exists` decides whether a host path is usable; a missing one is SKIPPED, not
// emitted — one stale path must never stop the whole stack from starting.
function generate(envValues, exists) {
	const profiles = botProfiles.listProfiles(envValues || {});
	const mounts = [];
	const skipped = [];
	for (const profile of profiles) {
		if (profile.name === botProfiles.DEFAULT_PROFILE) continue;
		if (typeof exists === 'function' && !exists(profile.hostPath)) {
			skipped.push(profile);
			continue;
		}
		mounts.push(profile);
	}
	if (!mounts.length) return { yaml: null, mounts: mounts, skipped: skipped };

	const lines = [HEADER, 'services:'];
	for (const service of SERVICES) {
		lines.push('  ' + service + ':');
		lines.push('    volumes:');
		for (const profile of mounts) {
			lines.push('      - ' + yamlQuote(profile.hostPath + ':/bots/' + profile.name + ':ro'));
		}
	}
	return { yaml: lines.join('\n') + '\n', mounts: mounts, skipped: skipped };
}

function readEnvValues() {
	try { return parse(fs.readFileSync(ENV_PATH, 'utf8')); } catch (e) { return {}; }
}

function hostPathExists(hostPath) {
	try { return fs.statSync(hostPath).isDirectory(); } catch (e) { return false; }
}

// Returns { written, removed, mounts, skipped }. Removing the file when nothing
// needs mounting matters: a leftover override naming a deleted path would make
// `docker compose up` fail outright.
function write(options) {
	options = options || {};
	const log = options.log || function () {};
	const result = generate(options.envValues || readEnvValues(), options.exists || hostPathExists);

	for (const profile of result.skipped) {
		log('[dojo] bot profile "' + profile.name + '" skipped — host path not found: ' + profile.hostPath);
	}
	if (!result.yaml) {
		let removed = false;
		try { fs.unlinkSync(OVERRIDE_PATH); removed = true; } catch (e) { /* nothing to remove */ }
		return { written: false, removed: removed, mounts: result.mounts, skipped: result.skipped };
	}
	// Skip the write when nothing changed: docker compose treats any override
	// mtime bump as a reason to recreate containers.
	let current = null;
	try { current = fs.readFileSync(OVERRIDE_PATH, 'utf8'); } catch (e) { /* not written yet */ }
	if (current === result.yaml) return { written: false, removed: false, mounts: result.mounts, skipped: result.skipped };

	fs.writeFileSync(OVERRIDE_PATH, result.yaml, 'utf8');
	log('[dojo] mounted ' + result.mounts.length + ' extra bot profile(s): '
		+ result.mounts.map(function (p) { return p.name; }).join(', '));
	return { written: true, removed: false, mounts: result.mounts, skipped: result.skipped };
}

if (require.main === module) {
	write({ log: console.log });
}

module.exports = {
	ENV_PATH: ENV_PATH,
	OVERRIDE_PATH: OVERRIDE_PATH,
	SERVICES: SERVICES,
	yamlQuote: yamlQuote,
	generate: generate,
	write: write
};
